"""Initial migration.

Revision ID: 921735883fd7
Revises: 
Create Date: 2024-02-05 22:18:17.452353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921735883fd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_model')
    # ### end Alembic commands ###
